export const en = {
    "": "",
    "Welcome": "Welcome",
    "Dashboard": "Dashboard",
    "Project": "Project",
    "Projects": "Projects",
    "Users": "Users",
    "Teams": "Teams",
    "Taps": "Taps",
    "Tap": "Tap",
    "Floors": "Floors",
    "Rooms": "Rooms",
    "Logout": "Logout",
    "Project name": "Project name",
    "Project description": "Project description",
    "Create project": "Create project",
    "Add project": "Add project",
    "Enter project description here": "Enter project description here",
    "Project created successfully": "Project created successfully",
    "Settings": "Settings",
    "Setting": "Setting",
    "Floor settings": "Floor settings",
    "Add floors": "Add floors",
    "Add product": "Add product",
    "Save": "Save",
    "Active": "Active",
    "Add": "Add",
    "Create": "Create",
    "Update": "Update",
    "Edit": "Edit",
    "Type":"Type",
    "Types": "Types",
    "Product": "Product",
    "Search": "Search",
    "swr": "Something went wrong. Try again later.",
    "Setting Added Successfully": "Product Added Successfully",
    "Setting Updated Successfully": "Product Updated Successfully",
    "Enter the tap type" : "Enter the tap type",
    "Tap type updated successfully": "Tap type updated successfully",
    "This tap type is already exist": "This tap type is already exist",
    "Enter the team name": "Enter the team name",
    "This team name is already exist": "This team name is already exist",
    "Team created successfully": "Team created successfully",
    "Name": "Name",
    "Shortcode": "Shortcode",
    "Email": "Email",
    "Password": "Password",
    "Select role": "Select role",
    "Select team": "Select team",
    "Select status": "Select status",
    "User updated successfully": "User updated successfully",
    "Team name updated successfully": "Team name updated successfully",
    "Are you sure you want to delete this project?": "Are you sure you want to delete this project?",
    "Project Deleted Successfully": "Project Deleted Successfully",
    "Quantity": "Quantity",
    "From": "From",
    "To": "To",
    "Reset": "Reset",
    "From the specified amount quantity should be": "From the specified amount quantity should be {{quantity}}",
    "Floors created successfully": "Floors created successfully",
    "Sections created successfully": "Sections created successfully",
    "Sections": "Sections",
    "Ausstehend": "Pending",
    "In Arbeit": "In Progress",
    "Fertig": "Finished",
    "No sections available": "No sections available",
    "Section updated successfully": "Section updated successfully",
    "Are you sure you want to delete this section?" : "Are you sure you want to delete this section?",
    "This section is locked, click on the lock button to unlock": "This section is locked. Click on the lock button to unlock",
    "This section is locked, kindly contact admin or leader": "This section is locked. Kindly contact admin or leader.",
    "Are you sure you want to delete this tap type?": "Are you sure you want to delete this tap type?",
    "Tap type deleted successfully": "Tap type deleted successfully",
    "No project assigned to you": "No project assigned to you.",
    "upload excel": "Upload Excel",
    "Upload excel": "Upload Excel",
    "Excel upload successfully": "Excel upload successfully",
    "Excel upload failed": "Excel upload failed"
}
