export const en = {
    "": "",
    "Welcome": "Welcome",
    "Dashboard": "Dashboard",
    "Project": "Project",
    "Projects": "Projects",
    "Users": "Users",
    "Teams": "Teams",
    "Taps": "Taps",
    "Tap": "Tap",
    "Logout": "Logout",
    "Project name": "Project name",
    "Project description": "Project description",
    "Create project": "Create project",
    "Add project": "Add project",
    "Enter project description here": "Enter project description here",
    "Project created successfully": "Project created successfully",
    "Settings": "Settings",
    "Setting": "Setting",
    "Floor settings": "Floor settings",
    "Add floors": "Add floors",
    "Add product": "Add product",
    "Save": "Save",
    "Active": "Active",
    "Add": "Add",
    "Create": "Create",
    "Update": "Update",
    "Edit": "Edit",
    "Type":"Type",
    "Types": "Types",
    "Product": "Product",
    "Search": "Search",
    "swr": "Something went wrong. Try again later.",
    "Setting Added Successfully": "Product Added Successfully",
    "Setting Updated Successfully": "Product Updated Successfully",
    "Enter the tap type" : "Enter the tap type",
    "Tap type updated successfully": "Tap type updated successfully",
    "This tap type is already exist": "This tap type is already exist",
    "Enter the team name": "Enter the team name",
    "This team name is already exist": "This team name is already exist",
    "Team created successfully": "Team created successfully",
    "Name": "Name",
    "Shortcode": "Shortcode",
    "Email": "Email",
    "Password": "Password",
    "Select role": "Select role",
    "Select team": "Select team",
    "User updated successfully": "User updated successfully",
    "Team name updated successfully": "Team name updated successfully",
    "Are you sure you want to delete this project?": "Are you sure you want to delete this project?",
    "Project Deleted Successfully": "Project Deleted Successfully",
    "Are you sure you want to delete this tap type?": "Are you sure you want to delete this tap type?",
    "Tap type deleted successfully": "Tap type deleted successfully"
}
