export const ge = {
    "": "",
    "Welcome" : "Herzlich willkommen",
    "Dashboard": "Dashboard",
    "Project": "Projekt",
    "Projects": "Projekte",
    "Users": "Benutzer",
    "Teams": "Teams",
    "Taps": "Wasserhähne",
    "Tap": "Zapfhahn",
    "Floors": "Böden",
    "Rooms": "Räume",
    "Logout": "Ausloggen",
    "Project name": "Projektname",
    "Project description": "Projektbeschreibung",
    "Create project": "Projekt erstellen",
    "Add project": "Projekt hinzufügen",
    "Enter project description here": "Geben Sie hier die Projektbeschreibung ein",
    "Project created successfully": "Projekt erfolgreich erstellt",
    "Settings": "Einstellungen",
    "Setting": "Rahmen",
    "Floor settings": "Bodeneinstellungen",
    "Add floors": "Böden hinzufügen",
    "Add product": "Produkt hinzufügen",
    "Save": "Speichern",
    "Active": "Aktiv",
    "Add": "Hinzufügen",
    "Create": "Erstellen",
    "Edit": "Bearbeiten",
    "Product": "Produkt",
    "Type":"Typen",
    "Types": "Typen",
    "Update": "Aktualisieren",
    "Search": "Suche",
    "swr": "Etwas ist schief gelaufen. Versuchen Sie es später noch einmal.",
    "Setting Added Successfully": "Produkt erfolgreich hinzugefügt",
    "Setting Updated Successfully": "Produkt erfolgreich aktualisiert",
    "Enter the tap type" : "Geben Sie den Tap-Typ ein",
    "Tap type updated successfully": "Tippen Sie auf Typ erfolgreich aktualisiert",
    "This tap type is already exist": "Dieser Tap-Typ ist bereits vorhanden",
    "Enter the team name": "Geben Sie den Teamnamen ein",
    "This team name is already exist": "Dieser Teamname ist bereits vorhanden",
    "Team created successfully": "Team erfolgreich erstellt",
    "Name": "Name",
    "Shortcode": "Shortcode",
    "Email": "Email",
    "Password": "Passwort",
    "Select role": "Rolle auswählen",
    "Select team": "Wählen Sie tem",
    "Select status": "Status auswählen",
    "User updated successfully": "Benutzer erfolgreich aktualisiert",
    "Team name updated successfully": "Teamname erfolgreich aktualisiert",
    "Are you sure you want to delete this project?": "Möchten Sie dieses Projekt wirklich löschen?",
    "Project Deleted Successfully": "Projekt erfolgreich gelöscht",
    "Quantity": "Menge",
    "From": "Von",
    "To": "Zu",
    "Reset": "Zurücksetzen",
    "From the specified amount quantity should be": "Ab der angegebenen Menge sollte die Menge sein {{quantity}}",
    "Floors created successfully": "Fußböden erfolgreich erstellt",
    "Sections created successfully": "Abschnitte erfolgreich erstellt",
    "Sections": "Abschnitte",
    "Ausstehend": "Ausstehend",
    "In Arbeit": "In Arbeit",
    "Fertig": "Fertig",
    "No sections available": "Keine Abschnitte verfügbar",
    "Section updated successfully": "Section updated successfully",
    "Are you sure you want to delete this section?" : "Möchten Sie diesen Abschnitt wirklich löschen?",
    "This section is locked, click on the lock button to unlock": "Dieser Abschnitt ist gesperrt. Klicken Sie zum Entsperren auf die Schaltfläche Sperren.",
    "This section is locked, kindly contact admin or leader": "Dieser Abschnitt ist gesperrt. Bitte wenden Sie sich an den Administrator oder Leiter.",
    "Are you sure you want to delete this tap type?": "Möchten Sie diesen Tap-Typ wirklich löschen?",
    "Tap type deleted successfully": "Tippen Sie auf Typ erfolgreich gelöscht",
    "No project assigned to you": "Ihnen ist kein Projekt zugeordnet.",
    "upload excel": "Excel Hochladen",
    "Upload excel": "Excel Hochladen",
    "Excel upload successfully": "Excel-Upload erfolgreich",
    "Excel upload failed": "Excel-Upload fehlgeschlagen"
}
