export const ge = {
    "": "",
    "Welcome" : "Herzlich willkommen",
    "Dashboard": "Dashboard",
    "Project": "Projekt",
    "Projects": "Projekte",
    "Users": "Benutzer",
    "Teams": "Teams",
    "Taps": "Wasserhähne",
    "Tap": "Zapfhahn",
    "Logout": "Ausloggen",
    "Project name": "Projektname",
    "Project description": "Projektbeschreibung",
    "Create project": "Projekt erstellen",
    "Add project": "Projekt hinzufügen",
    "Enter project description here": "Geben Sie hier die Projektbeschreibung ein",
    "Project created successfully": "Projekt erfolgreich erstellt",
    "Settings": "Einstellungen",
    "Setting": "Rahmen",
    "Floor settings": "Bodeneinstellungen",
    "Add floors": "Böden hinzufügen",
    "Add product": "Produkt hinzufügen",
    "Save": "Speichern",
    "Active": "Aktiv",
    "Add": "Hinzufügen",
    "Create": "Erstellen",
    "Edit": "Bearbeiten",
    "Product": "Produkt",
    "Type":"Typen",
    "Types": "Typen",
    "Update": "Aktualisieren",
    "Search": "Suche",
    "swr": "Etwas ist schief gelaufen. Versuchen Sie es später noch einmal.",
    "Setting Added Successfully": "Produkt erfolgreich hinzugefügt",
    "Setting Updated Successfully": "Produkt erfolgreich aktualisiert",
    "Enter the tap type" : "Geben Sie den Tap-Typ ein",
    "Tap type updated successfully": "Tippen Sie auf Typ erfolgreich aktualisiert",
    "This tap type is already exist": "Dieser Tap-Typ ist bereits vorhanden",
    "Enter the team name": "Geben Sie den Teamnamen ein",
    "This team name is already exist": "Dieser Teamname ist bereits vorhanden",
    "Team created successfully": "Team erfolgreich erstellt",
    "Name": "Name",
    "Shortcode": "Shortcode",
    "Email": "Email",
    "Password": "Passwort",
    "Select role": "Rolle auswählen",
    "Select team": "Wählen Sie tem",
    "User updated successfully": "Benutzer erfolgreich aktualisiert",
    "Team name updated successfully": "Teamname erfolgreich aktualisiert",
    "Are you sure you want to delete this project?": "Möchten Sie dieses Projekt wirklich löschen?",
    "Project Deleted Successfully": "Projekt erfolgreich gelöscht",
    "Are you sure you want to delete this tap type?": "Möchten Sie diesen Tap-Typ wirklich löschen?",
    "Tap type deleted successfully": "Tippen Sie auf Typ erfolgreich gelöscht"
}
