export const FETCH_PROJECTSETTINGS_REQUEST = 'FETCH_PROJECTSETTINGS_REQUEST';

export const FETCH_PROJECTSETTINGS_SUCCESS = 'FETCH_PROJECTSETTINGS_SUCCESS';

export const FETCH_PROJECTSETTINGS_FAIL = 'FETCH_PROJECTSETTINGS_FAIL';
